#!/bin/bash

##
## Macintosh laptop setup script, for ruby developers.
##

set -e

function pause() {
  read -p "$*" -n1
}

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    fancy_echo "Updating %s ..." "$1"
    gem update "$@"
  else
    fancy_echo "Installing %s ..." "$1"
    gem install "$@"
    rbenv rehash
  fi
}

fancy_echo "Justin's Mac OS X setup script"
pause 'Ctrl-c to quit, or press any key to continue...'

fancy_echo "Checking Homebrew"
if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  # curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  fancy_echo 'Add homebrew to your PATH, like so: export PATH="/usr/local/bin:$PATH"'
  export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi


######################################################################
# install Homebrew packages
fancy_echo "Updating Homebrew formulas ..."
brew update

fancy_echo "Fetching Brewfile from GitHub and installing packages..."
BREWFILE_URL="https://raw.githubusercontent.com/tomichj/homebrew-brewfile/master/Brewfile"
curl -fsSL "$BREWFILE_URL" | brew bundle --file=-



######################################################################
# Dotfiles
fancy_echo "Setting up dotfiles..."
git clone https://github.com/holman/dotfiles.git ~/.dotfiles
cd ~/.dotfiles
script/bootstrap


cd ~

# ######################################################################
# # ruby setup
# fancy_echo "Installing latest ruby..."

# # use rbenv to install ruby
# eval "$(rbenv init -)"
# ruby_version="$(rbenv install -l | sed -n 's/^[ ]*//p' | sed -n '/^[0-9]\.[0-9]\.[0-9]$/p' | tail -1)"
# if ! rbenv versions | grep -Fq "$ruby_version"; then
#   rbenv install -s "$ruby_version"
# fi

# rbenv global "$ruby_version"
# rbenv shell "$ruby_version"

# gem update --system

# # configure Bundler
# fancy_echo "Configuring Bundler ..."
# gem_install_or_update 'bundler'
# number_of_cores=$(sysctl -n hw.ncpu)
# bundle config --global jobs $((number_of_cores - 1))



#######################################################################
# extra configuration 
if [ -f "$HOME/.laptop.local" ]; then
  . "$HOME/.laptop.local"
fi

