#!/bin/bash

##
## Macintosh laptop setup script, for developers.
##

# consider checking for FDE instead of just enabling it.
# sudo fdesetup enable

function pause() {
  read -p "$*" -n1
}

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

set -e

gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    fancy_echo "Updating %s ..." "$1"
    gem update "$@"
  else
    fancy_echo "Installing %s ..." "$1"
    gem install "$@"
    rbenv rehash
  fi
}

echo "Justin's Mac OS X Installation Script."
pause 'Ctrl-c to quit, or press any key to continue...'

echo "Checking Homebrew"
if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    fancy_echo 'Add homebrew to your PATH, like so: export PATH="/usr/local/bin:$PATH"'
    export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

fancy_echo "Updating Homebrew formulas ..."
brew update
brew bundle --file=- <<EOF
tap 'caskroom/cask'
tap 'heroku/brew'
tap 'caskroom/fonts'

brew 'bash'
brew 'bash-completion'
brew 'git'
brew 'hub'
brew 'openssl'
brew 'gnutls'
brew 'tree'
brew 'coreutils'
brew 'findutils'
brew 'z'
brew 'grc'
brew 'spark'
brew 'imagemagick'
brew 'libyaml' # after openssl
brew 'switchaudio-osx'
brew "the_silver_searcher"

brew 'rbenv'
brew 'ruby-build'

brew 'heroku/brew/heroku'

cask 'dropbox'
cask '1password'
cask 'skype'
cask 'flux'
cask 'google-chrome'
cask 'firefox'
cask 'ngrok'

cask 'alfred'
cask 'keyboard-maestro'
cask 'superduper'
cask 'istat-menus'
cask 'viscosity'

cask 'vlc'
cask 'mplayerx'
cask 'plex-media-server'
cask 'plex-media-player'

cask 'the-unarchiver'

cask 'textmate'
cask 'sublime-text'
cask 'atom'
cask 'jetbrains-toolbox'

cask 'sourcetree'
cask 'diffmerge'
cask 'github'

cask 'postgres'
cask 'redis-app'
cask 'postico'

cask 'font-inconsolata'
cask 'font-source-code-pro'
cask 'font-anonymous-pro'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
EOF

fancy_echo 'Cleaning up old Homebrew formulae'
brew cleanup


######################################################################
# Set up bash
if ! grep -q "/usr/local/bin/bash" /etc/shells; then
  echo "adding /usr/loca/bin/bash to /etc/shells"
  sudo bash -c "echo '/usr/local/bin/bash' >> /etc/shells"
fi

if [ $SHELL != "/usr/local/bin/bash" ]; then
  chsh -s /usr/local/bin/bash
fi


######################################################################
# ruby setup

# use rbenv to install ruby
fancy_echo "Installing latest ruby..."

eval "$(rbenv init -)"
ruby_version="$(rbenv install -l | sed -n 's/^[ ]*//p' | sed -n '/^[0-9]\.[0-9]\.[0-9]$/p' | tail -1)"
if ! rbenv versions | grep -Fq "$ruby_version"; then
  rbenv install -s "$ruby_version"
fi

rbenv global "$ruby_version"
rbenv shell "$ruby_version"

gem update --system

# Bundler
gem_install_or_update 'bundler'

fancy_echo "Configuring Bundler ..."
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

fancy_echo 'Set up your dotfiles now, be sure to include /usr/local/bin in your path, like this: export PATH="/usr/local/bin:$PATH"'
fancy_echo 'Consider installing https://github.com/tomichj/dotfiles'

